import React, { createContext, useContext, useState, ReactNode } from 'react';

// 支援語言類型
export type Language = 'en-GB' | 'zh-HK'

interface Translations {
  [key: string]: string | { [key: string]: string }
}

// 語言上下文接口
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translations: Translations;
}

// 英式英文翻譯
const enTranslations: Translations = {
  // Nested structure for better organization
  toolCategory: {
    'all': 'All Tools',
    'ai-drawing': 'AI Drawing & Design',
    'video-content': 'Video Content',
    'image-editing': 'Image Editing',
    'ai-avatar': 'AI Avatar & Character',
    'audio-music': 'Audio & Music',
    'text-content': 'Text & Content',
    'business-tools': 'Business Tools',
    'creative-others': 'Creative & Others'
  },
  
  userGroup: {
    'all-users': 'All Users',
    'creative-professional': 'Creative & Design Professionals',
    'content-creator': 'Content Creators',
    'business-professional': 'Business & Marketing Professionals',
    'tech-developer': 'Tech & Development Professionals',
    'data-analyst': 'Data & Analytics Professionals',
    'educator': 'Education & Training Professionals',
    'media-professional': 'Media & Communication Professionals',
    'enterprise-manager': 'Enterprise Managers',
    'productivity-user': 'Productivity Users'
  },

  userTags: {
    // Creative & Design
    'digital-artist': 'Digital Artist',
    'concept-designer': 'Concept Designer',
    'illustrator': 'Illustrator',
    'creative-director': 'Creative Director',
    'professional-designer': 'Professional Designer',
    'graphic-designer': 'Graphic Designer',
    'brand-designer': 'Brand Designer',
    'designer': 'Designer',
    'artist': 'Artist',
    'creative-worker': 'Creative Worker',
    'ui-ux-designer': 'UI/UX Designer',
    'photographer': 'Photographer',
    
    // Content & Media
    'content-creator': 'Content Creator',
    'blogger': 'Blogger',
    'podcaster': 'Podcaster',
    'youtuber': 'YouTuber',
    'social-media-manager': 'Social Media Manager',
    'social-media-user': 'Social Media User',
    'copywriter': 'Copywriter',
    'journalist': 'Journalist',
    'editor': 'Editor',
    'video-editor': 'Video Editor',
    'video-creator': 'Video Creator',
    'video-producer': 'Video Producer',
    'music-creator': 'Music Creator',
    'music-producer': 'Music Producer',
    'audio-engineer': 'Audio Engineer',
    'audio-editor': 'Audio Editor',
    'animator': 'Animator',
    'animation-creator': 'Animation Creator',
    'visual-artist': 'Visual Artist',
    '3d-artist': '3D Artist',
    'filmmaker': 'Filmmaker',
    'marketing-content-creator': 'Marketing Content Creator',
    'professional-photographer': 'Professional Photographer',
    'photography-enthusiast': 'Photography Enthusiast',
    'photo-editor': 'Photo Editor',
    'general-user': 'General User',
    'individual-user': 'Individual User',
    'everyone': 'Everyone',
    'budget-conscious-user': 'Budget-Conscious User',
    'streamer': 'Streamer',
    'storyteller': 'Storyteller',
    'visual-effects-artist': 'Visual Effects Artist',
    'film-industry': 'Film Industry',
    'professional-director': 'Professional Director',
    'digital-marketing': 'Digital Marketing',
    'ecommerce-analytics': 'E-commerce Analytics',
    'website-management': 'Website Management',
    'ml-researcher': 'ML Researcher',
    'ai-engineer': 'AI Engineer',
    'ai-developer': 'AI Developer',
    'tech-team': 'Tech Team',
    'tech-leader': 'Tech Leader',
    'cybersecurity-specialist': 'Cybersecurity Specialist',
    'test-engineer': 'Test Engineer',
    'crm-administrator': 'CRM Administrator',
    'it-administrator': 'IT Administrator',
    'api-developer': 'API Developer',
    'internal-tools': 'Internal Tools',
    'rapid-prototyping': 'Rapid Prototyping',
    'rapid-development': 'Rapid Development',
    'prototype-design': 'Prototype Design',
    'saas-company': 'SaaS Company',
    'development-team': 'Development Team',
    'marketing-promoter': 'Marketing Promoter',
    'market-research': 'Market Research',
    'analyst': 'Analyst',
    'media-company': 'Media Company',
    
    // Business & Marketing
    'entrepreneur': 'Entrepreneur',
    'startup-founder': 'Startup Founder',
    'business-owner': 'Business Owner',
    'small-business-owner': 'Small Business Owner',
    'small-business': 'Small Business',
    'marketer': 'Marketer',
    'content-marketer': 'Content Marketer',
    'digital-marketer': 'Digital Marketer',
    'digital-marketing-agency': 'Digital Marketing Agency',
    'data-marketing-consultant': 'Data Marketing Consultant',
    'brand-manager': 'Brand Manager',
    'marketing-team': 'Marketing Team',
    'marketing-professional': 'Marketing Professional',
    'brand-marketing-specialist': 'Brand Marketing Specialist',
    'brand-marketing': 'Brand Marketing',
    'brand-consultant': 'Brand Consultant',
    'sales-professional': 'Sales Professional',
    'consultant': 'Consultant',
    'freelancer': 'Freelancer',
    'project-manager': 'Project Manager',
    'product-manager': 'Product Manager',
    'advertising-agency': 'Advertising Agency',
    'advertising-personnel': 'Advertising Personnel',
    'brand-team': 'Brand Team',
    'enterprise-user': 'Enterprise User',
    'corporate-training': 'Corporate Training',
    'corporate-trainer': 'Corporate Trainer',
    'hr-team': 'HR Team',
    'corporate-internal-training': 'Corporate Internal Training',
    'content-team': 'Content Team',
    'design-team': 'Design Team',
    'professional-editor': 'Professional Editor',
    'beginner': 'Beginner',
    'personal-creator': 'Personal Creator',
    'remote-worker': 'Remote Worker',
    'e-commerce': 'E-commerce',
    'e-commerce-business': 'E-commerce Business',
    'e-commerce-seller': 'E-commerce Seller',
    'agency': 'Agency',
    
    // Technology & Development
    'developer': 'Developer',
    'web-developer': 'Web Developer',
    'frontend-developer': 'Frontend Developer',
    'programmer': 'Programmer',
    'software-engineer': 'Software Engineer',
    'app-developer': 'App Developer',
    'game-developer': 'Game Developer',
    'data-scientist': 'Data Scientist',
    'ml-engineer': 'ML Engineer',
    'enterprise-ai-team': 'Enterprise AI Team',
    'ai-researcher': 'AI Researcher',
    'tech-professional': 'Tech Professional',
    'creative-tech-specialist': 'Creative Tech Specialist',
    'interaction-designer': 'Interaction Designer',
    'seo-specialist': 'SEO Specialist',
    'website-administrator': 'Website Administrator',
    'researcher': 'Researcher',
    'ai-enthusiast': 'AI Enthusiast',
    'twitter-creator': 'Twitter Creator',
    
    // Education & Research
    'teacher': 'Teacher',
    'educator': 'Educator',
    'educational-institution': 'Educational Institution',
    'student': 'Student',
    'academic': 'Academic',
    'trainer': 'Trainer',
    'academic-writing': 'Academic Writing',
    'business-writing': 'Business Writing',
    'english-learner': 'English Learner',
    'technical-learner': 'Technical Learner',
    'knowledge-worker': 'Knowledge Worker',
    'researcher': 'Researcher',
    'scholar': 'Scholar',
    'curriculum-developer': 'Curriculum Developer',
    'data-analyst': 'Data Analyst',
    'business-analyst': 'Business Analyst',
    'decision-maker': 'Decision Maker',
    'business-intelligence': 'Business Intelligence',
    'writer': 'Writer',
    'professional-writer': 'Professional Writer',
    'business-professional': 'Business Professional',
    'team-collaboration': 'Team Collaboration',
    'enterprise-team': 'Enterprise Team',
    'business-decision-maker': 'Business Decision Maker',
    
    // Other Professionals
    'analyst': 'Analyst',
    'manager': 'Manager',
    'executive': 'Executive',
    'administrator': 'Administrator',
    'assistant': 'Assistant',
    'creative-explorer': 'Creative Explorer',
    'enterprise-team': 'Enterprise Team',
    'business-consultant': 'Business Consultant',
    'sales-personnel': 'Sales Personnel',
    'founder': 'Founder',
    'enterprise': 'Enterprise',
    'gamer': 'Gamer',
    
    // Generic user types
    'anyone-needing-screen-recording': 'Anyone Needing Screen Recording',
    'meeting-professionals': 'Meeting Professionals',
    'presentation-creators': 'Presentation Creators',
    'productivity-seekers': 'Productivity Seekers',
    'multi-app-users': 'Multi-App Users',
    'quick-website-builders': 'Quick Website Builders',
    'information-seekers': 'Information Seekers',
    
    // Additional Missing Translations - Final Complete Set
    'ui-developer': 'UI Developer',
    'content-marketing': 'Content Marketing',
    'user-experience': 'User Experience',
    'enterprise-support': 'Enterprise Support',
    'enterprise-security-team': 'Enterprise Security Team',
    'corporate-training-department': 'Corporate Training Department',
    'corporate-communications': 'Corporate Communications',
    'enterprise-development': 'Enterprise Development',
    'enterprise-management': 'Enterprise Management',
    'fullstack-developer': 'Fullstack Developer',
    'online-course-creator': 'Online Course Creator',
    'busy-professional': 'Busy Professional',
    'freelance-writer': 'Freelance Writer',
    'ai-interested-small-business': 'AI-Interested Small Business',
    'customer-service-team': 'Customer Service Team',
    'backend-developer': 'Backend Developer',
    'finance-team': 'Finance Team',
    'coach': 'Coach',
    'software-developer': 'Software Developer',
    'creative-studio': 'Creative Studio',
    'creative-writer': 'Creative Writer',
    'career-development-professional': 'Career Development Professional',
    'virtual-streamer': 'Virtual Streamer',
    'visually-impaired': 'Visually Impaired',
    'news-organization': 'News Organisation',
    'gaming-enthusiast': 'Gaming Enthusiast',
    'e-commerce-brand': 'E-commerce Brand',
    'team-leader': 'Team Leader',
    'web-designer': 'Web Designer',
    'advertising-creative': 'Advertising Creative',
    'course-creator': 'Course Creator',
    'sales-team': 'Sales Team',
    'student-developer': 'Student Developer',
    'enterprise-marketing-team': 'Enterprise Marketing Team'
  },

  button: {
    visitWebsite: 'Visit Website',
    showMore: 'Show More',
    showLess: 'Show Less',
    resetFilters: 'Reset Filters',
    expand: 'Expand',
    collapse: 'Collapse'
  },

  label: {
    targetUsers: 'Target Users',
    smartFilter: 'Smart Filter',
    toolType: 'Tool Type',
    userRole: 'User Role',
    filterDescription: 'Find the perfect AI tools for your needs',
    resultsShowing: 'Showing',
    resultsFor: 'for',
    resultsCategory: 'category',
    resultsSuitableFor: 'Suitable for',
    resultsAll: 'All',
    toolsFound: 'tools found'
  },

  page: {
    title: 'Recommended AI Tools',
    subtitle: 'Discover 101 powerful AI tools to enhance your productivity and creativity'
  },

  // Tools Page - Main Content (keeping backwards compatibility)
  'tools.pageTitle': 'Recommended AI Tools',
  'tools.pageSubtitle': 'Discover 101 powerful AI tools to enhance your productivity and creativity',
  'tools.smartFilter': 'Smart Filter',
  'tools.filterDescription': 'Find the perfect AI tools for your needs',
  'tools.allTools': 'All Tools',
  'tools.toolsFound': 'tools found',
  'tools.noToolsFound': 'No tools found',
  'tools.noToolsMessage': 'Try adjusting your filters to see more results',
  'tools.visitWebsite': 'Visit Website',
  'tools.targetUsers': 'Target Users',
  'tools.showMore': 'Show More',
  'tools.showLess': 'Show Less',
  'tools.toolType': 'Tool Type',
  'tools.userRole': 'User Role',
  'tools.resetFilters': 'Reset Filters',
  'tools.resultsShowing': 'Showing',
  'tools.resultsFor': 'for',
  'tools.resultsCategory': 'category',
  'tools.resultsSuitableFor': 'Suitable for',
  'tools.resultsAll': 'All',
  


  // 導航
  'nav.home': 'Home',
  'nav.about': 'About Us',
  'nav.courses': 'Courses',
  'nav.tools': 'Tools',
  'nav.blog': 'Blog',
  'nav.signin': 'Sign In',
  'nav.signup': 'Sign Up',
  
  // Hero Section
  'hero.badge': 'AI in Business',
  'hero.title': 'AI: The Future of',
  'hero.title1': 'AI: The Future of',
  'hero.titleHighlight': 'Learning',
  'hero.subtitle': 'Practical AI training designed for Hong Kong professionals',
  'hero.description': 'Learn AI skills that immediately help you save time and boost efficiency',
  'hero.cta1': 'Start Free Trial',
  'hero.cta2': 'View Courses',
  'hero.chooseProgram': 'Choose Your Program',
  
  // Technology Showcase
  'tech.title': 'Powered by Leading Technologies',
  'tech.subtitle': 'We master the tools that drive modern business automation',
  'tech.n8n': 'Workflow Automation',
  'tech.make': 'Integration Platform',
  'tech.zapier': 'App Connections',
  'tech.python': 'Data Processing',
  'tech.javascript': 'Web Development',
  'tech.openai': 'AI Integration',
  
  // Testimonials
  'testimonials.title': 'What Our Clients Say',
  'testimonials.subtitle': 'Real feedback from businesses using our AI automation solutions',
  'testimonials.testimonial1.quote': 'AI Formula helped us build a custom WhatsApp automation system that handles customer inquiries 24/7. No more missed messages and our response time improved dramatically.',
  'testimonials.testimonial1.author': 'Wong Ka Ming',
  'testimonials.testimonial1.service': 'Custom Automation Solution',
  'testimonials.testimonial1.company': 'Local Trading Company',
  'testimonials.testimonial2.quote': 'Their team built us a custom business automation system that connects our inventory, orders, and accounting. Everything runs smoothly now.',
  'testimonials.testimonial2.author': 'Chan Siu Fung',
  'testimonials.testimonial2.service': 'Business Automation',
  'testimonials.testimonial2.company': 'Small Manufacturing Business',
  'testimonials.testimonial3.quote': 'The custom AI chatbot they created for our restaurant handles reservations and orders perfectly. It understands Cantonese and English!',
  'testimonials.testimonial3.author': 'Lam Mei Ling',
  'testimonials.testimonial3.service': 'Custom AI Chatbot',
  'testimonials.testimonial3.company': 'Family Restaurant',
  
  // Automation Journey
  'journey.title': 'Your Automation Journey',
  'journey.subtitle': 'Our proven 4-step process ensures successful automation implementation',
  'journey.step1.title': 'Discovery Call',
  'journey.step1.description': 'We understand your needs and identify automation opportunities',
  'journey.step2.title': 'Strategy & Design',
  'journey.step2.description': 'Create a detailed blueprint tailored to your business processes',
  'journey.step3.title': 'Build & Integrate',
  'journey.step3.description': 'Develop and seamlessly integrate your custom automation solution',
  'journey.step4.title': 'Launch & Support',
  'journey.step4.description': 'Deploy your solution and provide ongoing support and optimization',
  
  // Instructors
  'instructors.title': 'Meet Our',
  'instructors.titleHighlight': 'Expert Instructors',
  'instructors.subtitle': 'Learn from industry leaders who combine deep technical expertise with real-world business experience in AI and automation.',
  'instructors.experience': 'Experience',
  'instructors.professionalJourney': 'Professional Journey',
  'instructors.teachingPhilosophy': 'Teaching Philosophy',
  'instructors.keyQualifications': 'Key Qualifications',
  'instructors.viewProfile': 'View Full Profile',
  
  // Kenneth - First Instructor
  'instructors.sarah.name': 'Kenneth',
  'instructors.sarah.title': 'AI Marketing Developer & Automation Specialist',
  'instructors.sarah.specialty': 'AI Tools & Marketing Automation',
  'instructors.sarah.experience': '4+ years',
  'instructors.sarah.biography': 'Kenneth is a pioneering AI marketing developer who specialises in cutting-edge AI tools, automation systems, and strategic implementation. Over 4 years of intensive AI learning, he has mastered the art of transforming traditional marketing approaches through artificial intelligence and automation technologies.',
  'instructors.sarah.philosophy': 'AI is fundamentally transforming how we live and work. The future belongs to those who embrace AI today. I help individuals and businesses get ahead of the curve by mastering AI tools and automation before the masses catch up.',
  'instructors.sarah.qual1': 'AI Marketing Automation Expert',
  'instructors.sarah.qual2': 'Advanced AI Tools Implementation',
  'instructors.sarah.qual3': 'Strategic AI Business Integration',
  'instructors.sarah.qual4': 'Future-Ready Marketing Systems',
  
  // David - Second Instructor
  'instructors.david.name': 'David',
  'instructors.david.title': 'Business Automation & AI Integration Specialist',
  'instructors.david.specialty': 'Automation & AI Solutions',
  'instructors.david.experience': '7+ years',
  'instructors.david.biography': 'David is a business automation expert who has spent 7+ years helping companies eliminate overwork and streamline operations. He specialises in creating powerful automation workflows using Make.com, n8n, and AI tools.',
  'instructors.david.philosophy': 'Automation should solve real business problems and reduce overwork. I help businesses implement all-in-one AI solutions that transform operations.',
  'instructors.david.qual1': 'Make.com & n8n Automation Expert',
  'instructors.david.qual2': 'Business Process Optimization',
  'instructors.david.qual3': 'AI-Powered Content Management',
  'instructors.david.qual4': 'All-in-One Business Solutions',
  
  // Ken - Third Instructor
  'instructors.emily.name': 'Ken',
  'instructors.emily.title': 'Custom Business Developer & AI Automation Specialist',
  'instructors.emily.specialty': 'Custom Coding & AI Automation',
  'instructors.emily.experience': '5+ years',
  'instructors.emily.biography': 'Ken is a skilled custom business developer with 5+ years of coding experience, specializing in creating tailored business solutions and AI automation systems that help businesses work faster and run more efficiently.',
  'instructors.emily.philosophy': 'Code should make work faster and businesses run smoother. I create custom solutions that integrate AI automation to eliminate bottlenecks and accelerate business processes.',
  'instructors.emily.qual1': 'Custom Business Application Development',
  'instructors.emily.qual2': 'AI Automation Integration Expert',
  'instructors.emily.qual3': 'Performance Optimization Specialist',
  'instructors.emily.qual4': 'Rapid Development Solutions',
  
  // Jason - Fourth Instructor
  'instructors.michael.name': 'Jason',
  'instructors.michael.title': 'Professional Developer & Custom Automation Specialist',
  'instructors.michael.specialty': 'Coding & Custom Automation',
  'instructors.michael.experience': '8+ years',
  'instructors.michael.biography': 'Jason is a professional developer with 8+ years of coding experience, specializing in LLM chatbox development, MCP integration, and web applications. He has been intensively learning AI to uplevel coding skills.',
  'instructors.michael.philosophy': 'No AI, no life! AI can change more than you think. Every developer needs to embrace AI to stay relevant and create extraordinary solutions.',
  'instructors.michael.qual1': 'LLM Chatbox Development Expert',
  'instructors.michael.qual2': 'MCP Integration Specialist',
  'instructors.michael.qual3': 'Full-Stack Web Development',
  'instructors.michael.qual4': 'AI-Enhanced Coding Solutions',
  
  // Contact
  'contact.title': 'Get In Touch',
  'contact.subtitle': 'Ready to transform your business with AI?',
  'contact.form.title': 'Send Us a Message',
  'contact.form.description': 'Fill out the form below and we\'ll get back to you within 24 hours',
  'contact.form.name': 'Full Name',
  'contact.form.email': 'Email Address',
  'contact.form.message': 'How can we help you?',
  'contact.form.send': 'Send Message',
  'contact.info.emailUs': 'Email Us',
  'contact.info.emailDescription': 'Get quick responses to your questions',
  'contact.info.callUs': 'Call Us',
  'contact.info.phoneDescription': 'Mon-Fri 9AM-6PM HKT',
  'contact.info.visitUs': 'Visit Us',
  'contact.info.visitDescription': 'Schedule an appointment',
  
  // Toast Messages
  'toast.messageSent': 'Message Sent!',
  'toast.messageDescription': 'Thank you for your interest. We\'ll get back to you within 24 hours.',
  
  // Features
  'features.title': 'Why Choose AI Formula?',
  'features.subtitle': 'Professional AI training designed for Hong Kong market',
  'features.practical.title': 'Practical Applications',
  'features.practical.desc': 'Real business scenarios and hands-on projects',
  'features.expert.title': 'Expert Instructors',
  'features.expert.desc': 'Industry professionals with proven track records',
  'features.support.title': 'Ongoing Support',
  'features.support.desc': 'Continuous learning support and community',
  'features.local.title': 'Local Focus',
  'features.local.desc': 'Designed specifically for Hong Kong business environment',
  
  // Courses
  'courses.title': 'Featured Courses',
  'courses.subtitle': 'Comprehensive AI training programs',
  'courses.beginner': 'Beginner',
  'courses.intermediate': 'Intermediate',
  'courses.advanced': 'Advanced',
  'courses.hours': 'hours',
  'courses.students': 'students',
  'courses.rating': 'rating',
  'courses.enroll': 'Enroll Now',
  'courses.learnMore': 'Learn More',
  
  // Footer
  'footer.company': 'AI Formula',
  'footer.description': 'Professional AI training for Hong Kong businesses',
  'footer.links': 'Quick Links',
  'footer.courses': 'Courses',
  'footer.about': 'About',
  'footer.contact': 'Contact',
  'footer.support': 'Support',
  'footer.legal': 'Legal',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.newsletter': 'Newsletter',
  'footer.newsletter.desc': 'Get the latest AI updates and course announcements',
  'footer.newsletter.placeholder': 'Enter your email',
  'footer.newsletter.button': 'Subscribe',
  'footer.social': 'Follow Us',
  'footer.rights': 'All rights reserved',
  
  // Course Details
  'course.duration': 'Duration',
  'course.level': 'Level',
  'course.language': 'Language',
  'course.certificate': 'Certificate',
  'course.overview': 'Course Overview',
  'course.curriculum': 'Curriculum',
  'course.instructor': 'Instructor',
  'course.reviews': 'Reviews',
  'course.whatYouLearn': 'What You\'ll Learn',
  'course.requirements': 'Requirements',
  'course.includes': 'This course includes',
  'course.enroll': 'Enroll Course',
  'course.preview': 'Preview Course',
  
  // Learning
  'learning.progress': 'Progress',
  'learning.completed': 'Completed',
  'learning.continue': 'Continue Learning',
  'learning.start': 'Start Learning',
  'learning.next': 'Next Lesson',
  'learning.previous': 'Previous Lesson',
  'learning.notes': 'Notes',
  'learning.resources': 'Resources',
  'learning.quiz': 'Quiz',
  'learning.exercise': 'Exercise',
  'learning.download': 'Download',
  
  // Blog
  'blog.title': 'Latest Insights',
  'blog.subtitle': 'AI Formula Expert Insights',
  'blog.readMore': 'Read More',
  'blog.category': 'Category',
  'blog.tags': 'Tags',
  'blog.author': 'Author',
  'blog.date': 'Date',
  'blog.readTime': 'read time',
  'blog.share': 'Share',
  'blog.like': 'Like',
  'blog.comment': 'Comment',
  
  // Auth
  'auth.login': 'Login',
  'auth.signup': 'Sign Up',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.rememberMe': 'Remember Me',
  'auth.loginButton': 'Login',
  'auth.signupButton': 'Sign Up',
  'auth.or': 'Or',
  'auth.googleLogin': 'Continue with Google',
  'auth.facebookLogin': 'Continue with Facebook',
  'auth.hasAccount': 'Already have an account?',
  'auth.noAccount': 'Don\'t have an account?',
  'auth.loginDescription': 'Enter your email and password to sign in to your account',
  'auth.signupDescription': 'Create your account to start learning with AI Formula',
  'auth.emailPlaceholder': 'Please enter your email address',
  'auth.passwordPlaceholder': 'Please enter your password',
  'auth.confirmPasswordPlaceholder': 'Please re-enter your password',
  
  // Dashboard
  'dashboard.welcome': 'Welcome back',
  'dashboard.overview': 'Overview',
  'dashboard.myCourses': 'My Courses',
  'dashboard.progress': 'Progress',
  'dashboard.achievements': 'Achievements',
  'dashboard.settings': 'Settings',
  'dashboard.profile': 'Profile',
  'dashboard.notifications': 'Notifications',
  'dashboard.billing': 'Billing',
  'dashboard.support': 'Support',
  
  // User Avatar Dropdown
  'userMenu.dashboard': 'Dashboard',
  'userMenu.settings': 'Settings',
  'userMenu.profile': 'Profile',
  'userMenu.signOut': 'Sign Out',
  'userMenu.greeting': 'Hello',
  
  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.warning': 'Warning',
  'common.info': 'Info',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.view': 'View',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.sort': 'Sort',
  'common.reset': 'Reset',
  'common.apply': 'Apply',
  'common.close': 'Close',
  'common.open': 'Open',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.ok': 'OK',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.submit': 'Submit',
  'common.confirm': 'Confirm',
  'common.more': 'More',
  'common.less': 'Less',
  'common.show': 'Show',
  'common.hide': 'Hide',
  'common.expand': 'Expand',
  'common.collapse': 'Collapse',
  
  // Tools Page
  'tools.title': 'Useful Tools',
  'tools.subtitle': 'Discover powerful tools to enhance your productivity and creativity',
  'tools.categories.aiVideo': 'AI Video Tools',
  'tools.categories.dataTools': 'Data Tools',
  'tools.categories.designTools': 'Design Tools', 
  'tools.categories.marketingTools': 'AI Marketing Tools',
  
  // Design Tools
  'tools.freepik.title': 'Freepik - Free Design Resources',
  'tools.freepik.description': 'Access millions of free vectors, photos, and graphics for your projects. Create stunning visuals without breaking the budget.',
  'tools.freepik.tag': 'Free Design',
  'tools.freepik.visitSite': 'Visit Freepik',
  
  // Data Tools
  'tools.mem0.title': 'Mem0 - OpenMemory MCP',
  'tools.mem0.description': 'Advanced memory management and conversation persistence for AI applications. Build smarter AI systems with contextual memory.',
  'tools.mem0.tag': 'AI Memory',
  'tools.mem0.visitSite': 'Visit Mem0',
  
  'tools.chat4data.title': 'Chat4Data - AI Web Data Extraction',
  'tools.chat4data.description': 'Extract structured data from any website through natural conversation. No coding required - AI automatically detects and extracts valuable data.',
  'tools.chat4data.tag': 'Data Extraction',
  'tools.chat4data.visitSite': 'Visit Chat4Data',
  
  // AI Video Tools
  'tools.hailuo.title': 'Hailuo AI - Top AI Video Generation',
  'tools.hailuo.description': 'Try Hailuo 02 by Minimax for free, a top-performing AI video tool that transforms images into stunning HD videos in minutes.',
  'tools.hailuo.tag': 'AI Video',
  'tools.hailuo.visitSite': 'Visit Hailuo AI',
  
  'tools.higgsfield.title': 'Higgsfield AI - Visual Effects',
  'tools.higgsfield.description': 'AI-powered camera controls and visual effects tools. From explosions to surreal transformations, create cinematic visual effects.',
  'tools.higgsfield.tag': 'Visual Effects',
  'tools.higgsfield.visitSite': 'Visit Higgsfield',
  
  'tools.unstableml.title': 'UnstableML - AI Avatars',
  'tools.unstableml.description': 'Personalized AI avatars for product demos, tutorials, and UGC content creation. Clone your face and voice for authentic content.',
  'tools.unstableml.tag': 'AI Avatars',
  'tools.unstableml.visitSite': 'Visit UnstableML',
  
  'tools.4dv.title': '4DV.AI - AI Video Platform',
  'tools.4dv.description': 'Advanced AI video generation and editing platform with professional-grade video creation tools and effects.',
  'tools.4dv.tag': 'AI Video',
  'tools.4dv.visitSite': 'Visit 4DV.AI',
  
  'tools.seaweedapt.title': 'Seaweed APT2 - Real-Time Video',
  'tools.seaweedapt.description': 'Autoregressive adversarial post-training for real-time interactive video generation. Stream high-quality videos at 24fps with minimal latency.',
  'tools.seaweedapt.tag': 'Real-Time Video',
  'tools.seaweedapt.visitSite': 'Visit Seaweed APT',
  
  // Marketing Tools  
  'tools.headai.title': 'Head AI - World\'s First AI Marketer',
  'tools.headai.description': 'Professional AI taking over your influencer & affiliate marketing. Not a tool, but a complete AI marketing team that handles campaigns end-to-end.',
  'tools.headai.tag': 'AI Marketing',
  'tools.headai.visitSite': 'Visit Head AI',
  
  // 404 Page
  'notFound.title': 'Oops! Page Not Found',
  'notFound.subtitle': 'The page you\'re looking for doesn\'t exist',
  'notFound.description': 'Don\'t worry, it happens to the best of us. The page might have been moved, deleted, or you might have mistyped the URL.',
  'notFound.error404': '404',
  'notFound.pageNotFound': 'Page Not Found',
  'notFound.quickLinks': 'Quick Links',
  'notFound.backToHome': 'Back to Home',
  'notFound.contactSupport': 'Contact Support',
  'notFound.reportProblem': 'Report Problem',
  'notFound.currentPath': 'Looking for',
  'notFound.timestamp': 'Time',
  'notFound.needHelp': 'Need Help?',
}

// 中文翻譯
const zhTranslations: Translations = {
  // 巢狀結構以便更好的組織
  toolCategory: {
    'all': '全部工具',
    'ai-drawing': 'AI繪圖設計',
    'video-content': '影片相關',
    'image-editing': '圖片編輯',
    'ai-avatar': 'AI虛擬人',
    'audio-music': '音樂音頻',
    'text-content': '文字內容',
    'business-tools': '商業工具',
    'creative-others': '創意其他'
  },
  
  userGroup: {
    'all-users': '全部用戶',
    'creative-professional': '創意設計師',
    'content-creator': '內容創作者',
    'business-professional': '商業營銷人員',
    'tech-developer': '技術開發者',
    'data-analyst': '數據分析相關',
    'educator': '教育培訓人員',
    'media-professional': '媒體傳播人員',
    'enterprise-manager': '企業管理者',
    'productivity-user': '效率提升用戶'
  },

  userTags: {
    // 創意設計
    'digital-artist': '數字藝術家',
    'concept-designer': '概念設計師',
    'illustrator': '插畫家',
    'creative-director': '創意總監',
    'professional-designer': '專業設計師',
    'graphic-designer': '平面設計師',
    'brand-designer': '品牌設計師',
    'designer': '設計師',
    'artist': '藝術家',
    'creative-worker': '創意工作者',
    'ui-ux-designer': 'UI/UX設計師',
    'photographer': '攝影師',
    
    // 內容媒體
    'content-creator': '內容創作者',
    'blogger': '博客作者',
    'podcaster': '播客主',
    'youtuber': 'YouTuber',
    'social-media-manager': '社交媒體經理',
    'social-media-user': '社交媒體用戶',
    'copywriter': '文案撰寫人',
    'journalist': '記者',
    'editor': '編輯',
    'video-editor': '影片編輯',
    'video-creator': '影片創作者',
    'video-producer': '影片製作人',
    'music-creator': '音樂創作者',
    'music-producer': '音樂製作人',
    'audio-engineer': '音頻工程師',
    'audio-editor': '音頻編輯',
    'animator': '動畫師',
    'animation-creator': '動畫創作者',
    'visual-artist': '視覺藝術家',
    '3d-artist': '3D藝術家',
    'filmmaker': '電影製作人',
    'marketing-content-creator': '營銷內容創作者',
    'professional-photographer': '專業攝影師',
    'photography-enthusiast': '攝影愛好者',
    'photo-editor': '照片編輯',
    'general-user': '通用用戶',
    'individual-user': '個人用戶',
    'everyone': '所有人',
    'budget-conscious-user': '預算意識用戶',
    'streamer': '直播主',
    'storyteller': '故事講述者',
    'visual-effects-artist': '視覺效果藝術家',
    'film-industry': '電影行業',
    'professional-director': '專業導演',
    'digital-marketing': '數位行銷',
    'ecommerce-analytics': '電子商務分析',
    'website-management': '網站管理',
    'ml-researcher': '機器學習研究員',
    'ai-engineer': 'AI工程師',
    'ai-developer': 'AI開發者',
    'tech-team': '技術團隊',
    'tech-leader': '技術主管',
    'cybersecurity-specialist': '網絡安全專家',
    'test-engineer': '測試工程師',
    'crm-administrator': 'CRM管理員',
    'it-administrator': 'IT管理員',
    'api-developer': 'API開發者',
    'internal-tools': '內部工具',
    'rapid-prototyping': '快速原型製作',
    'rapid-development': '快速開發',
    'prototype-design': '原型設計',
    'saas-company': 'SaaS公司',
    'development-team': '開發團隊',
    'marketing-promoter': '市場推廣人員',
    'market-research': '市場研究',
    'analyst': '分析師',
    'media-company': '媒體公司',
    
    // 商業營銷
    'entrepreneur': '企業家',
    'startup-founder': '創業者',
    'business-owner': '企業主',
    'small-business-owner': '小企業主',
    'small-business': '小型企業',
    'marketer': '營銷人員',
    'content-marketer': '內容營銷人員',
    'digital-marketer': '數位營銷人員',
    'digital-marketing-agency': '數位行銷公司',
    'data-marketing-consultant': '數據行銷顧問',
    'brand-manager': '品牌經理',
    'marketing-team': '行銷團隊',
    'marketing-professional': '市場營銷人員',
    'brand-marketing-specialist': '品牌行銷專家',
    'brand-marketing': '品牌行銷',
    'brand-consultant': '品牌顧問',
    'sales-professional': '銷售專業人員',
    'consultant': '顧問',
    'freelancer': '自由職業者',
    'project-manager': '項目經理',
    'product-manager': '產品經理',
    'advertising-agency': '廣告公司',
    'advertising-personnel': '廣告人員',
    'brand-team': '品牌團隊',
    'enterprise-user': '企業用戶',
    'corporate-training': '企業培訓',
    'corporate-trainer': '企業培訓師',
    'hr-team': '人力資源團隊',
    'corporate-internal-training': '企業內部培訓',
    'content-team': '內容團隊',
    'design-team': '設計團隊',
    'professional-editor': '專業編輯',
    'beginner': '初學者',
    'personal-creator': '個人創作者',
    'remote-worker': '遠端工作者',
    'e-commerce': '電子商務',
    'e-commerce-business': '電子商務企業',
    'e-commerce-seller': '電子商務賣家',
    'agency': '代理商',
    
    // 技術開發
    'developer': '開發者',
    'web-developer': '網頁開發者',
    'frontend-developer': '前端開發者',
    'programmer': '程式員',
    'software-engineer': '軟體工程師',
    'app-developer': '應用程式開發者',
    'game-developer': '遊戲開發者',
    'data-scientist': '數據科學家',
    'ml-engineer': '機器學習工程師',
    'enterprise-ai-team': '企業AI團隊',
    'ai-researcher': 'AI研究員',
    'tech-professional': '技術專業人員',
    'creative-tech-specialist': '創意科技專家',
    'interaction-designer': '互動設計師',
    'seo-specialist': 'SEO專家',
    'website-administrator': '網站管理員',
    'researcher': '研究人員',
    'ai-enthusiast': 'AI愛好者',
    'twitter-creator': 'Twitter創作者',
    
    // 教育研究
    'teacher': '教師',
    'educator': '教育工作者',
    'educational-institution': '教育機構',
    'student': '學生',
    'academic': '學者',
    'trainer': '培訓師',
    'academic-writing': '學術寫作',
    'business-writing': '商業寫作',
    'english-learner': '英語學習者',
    'technical-learner': '技術學習者',
    'knowledge-worker': '知識工作者',
    'researcher': '研究人員',
    'scholar': '學者',
    'curriculum-developer': '課程開發者',
    'data-analyst': '數據分析相關',
    'business-analyst': '商業分析相關',
    'decision-maker': '決策者',
    'business-intelligence': '商業智慧',
    'writer': '寫作者',
    'professional-writer': '專業寫作者',
    'business-professional': '商業專業人士',
    'team-collaboration': '團隊合作',
    'enterprise-team': '企業團隊',
    'business-decision-maker': '企業決策者',
    
    // 其他專業人員
    'analyst': '分析師',
    'manager': '經理',
    'executive': '主管',
    'administrator': '管理員',
    'assistant': '助理',
    'creative-explorer': '創意探索者',
    'enterprise-team': '企業團隊',
    'business-consultant': '商業顧問',
    'sales-personnel': '銷售人員',
    'founder': '創始人',
    'enterprise': '企業',
    'gamer': '遊戲玩家',
    
    // 通用用戶類型
    'anyone-needing-screen-recording': '任何需要螢幕錄製的人',
    'meeting-professionals': '會議專業人士',
    'presentation-creators': '簡報創作者',
    'productivity-seekers': '生產力追求者',
    'multi-app-users': '多應用程式用戶',
    'quick-website-builders': '快速網站建構者',
    'information-seekers': '資訊尋求者',
    
    // Additional Missing Translations - Final Complete Set
    'ui-developer': 'UI Developer',
    'content-marketing': 'Content Marketing',
    'user-experience': 'User Experience',
    'enterprise-support': 'Enterprise Support',
    'enterprise-security-team': 'Enterprise Security Team',
    'corporate-training-department': 'Corporate Training Department',
    'corporate-communications': 'Corporate Communications',
    'enterprise-development': 'Enterprise Development',
    'enterprise-management': 'Enterprise Management',
    'fullstack-developer': 'Fullstack Developer',
    'online-course-creator': 'Online Course Creator',
    'busy-professional': 'Busy Professional',
    'freelance-writer': 'Freelance Writer',
    'ai-interested-small-business': 'AI-Interested Small Business',
    'customer-service-team': 'Customer Service Team',
    'backend-developer': 'Backend Developer',
    'finance-team': 'Finance Team',
    'coach': 'Coach',
    'software-developer': 'Software Developer',
    'creative-studio': 'Creative Studio',
    'creative-writer': 'Creative Writer',
    'career-development-professional': 'Career Development Professional',
    'virtual-streamer': 'Virtual Streamer',
    'visually-impaired': 'Visually Impaired',
    'news-organization': 'News Organisation',
    'gaming-enthusiast': 'Gaming Enthusiast',
    'e-commerce-brand': 'E-commerce Brand',
    'team-leader': 'Team Leader',
    'web-designer': 'Web Designer',
    'advertising-creative': 'Advertising Creative',
    'course-creator': 'Course Creator',
    'sales-team': 'Sales Team',
    'student-developer': 'Student Developer',
    'enterprise-marketing-team': 'Enterprise Marketing Team'
  },

  button: {
    visitWebsite: '訪問網站',
    showMore: '顯示更多',
    showLess: '顯示更少',
    resetFilters: '重置篩選',
    expand: '展開',
    collapse: '收合'
  },

  label: {
    targetUsers: '目標用戶',
    smartFilter: '智能篩選器',
    toolType: '工具類型',
    userRole: '用戶角色',
    filterDescription: '為您的需求找到完美的 AI 工具',
    resultsShowing: '顯示',
    resultsFor: '於',
    resultsCategory: '類別',
    resultsSuitableFor: '適合',
    resultsAll: '全部',
    toolsFound: '個工具'
  },

  page: {
    title: '推薦 AI 工具',
    subtitle: '探索 101 個強大的 AI 工具，提升您的生產力和創造力'
  },

  // 導航
  'nav.home': '首頁',
  'nav.about': '關於我們',
  'nav.courses': '課程',
  'nav.tools': '推薦 AI 工具',
  'nav.blog': '部落格',
  'nav.signin': '登入',
  'nav.signup': '註冊',
  
  // Tools Page - 工具頁面
  'tools.pageTitle': '推薦 AI 工具',
  'tools.pageSubtitle': '探索 101 個強大的 AI 工具，提升您的生產力和創造力',
  'tools.smartFilter': '智能篩選器',
  'tools.filterDescription': '為您的需求找到完美的 AI 工具',
  'tools.allTools': '全部工具',
  'tools.toolsFound': '個工具',
  'tools.noToolsFound': '找不到工具',
  'tools.noToolsMessage': '嘗試調整篩選條件以查看更多結果',
  'tools.visitWebsite': '訪問網站',
  'tools.targetUsers': '目標用戶',
  'tools.showMore': '顯示更多',
  'tools.showLess': '顯示更少',
  'tools.toolType': '工具類型',
  'tools.userRole': '用戶角色',
  'tools.resetFilters': '重置篩選',
  'tools.resultsShowing': '顯示',
  'tools.resultsFor': '於',
  'tools.resultsCategory': '類別',
  'tools.resultsSuitableFor': '適合',
  'tools.resultsAll': '全部',
  
  // Hero Section
  'hero.badge': '商業AI',
  'hero.title': 'AI：未來的學習',
  'hero.title1': 'AI：未來的',
  'hero.titleHighlight': '學習',
  'hero.subtitle': '專為香港專業人士設計的實用AI培訓',
  'hero.description': '學習能立即幫助您節省時間和提高效率的AI技能',
  'hero.cta1': '開始免費試用',
  'hero.cta2': '查看課程',
  'hero.chooseProgram': '選擇您的課程',
  
  // Technology Showcase
  'tech.title': '採用領先技術',
  'tech.subtitle': '我們精通驅動現代商業自動化的工具',
  'tech.n8n': '工作流程自動化',
  'tech.make': '整合平台',
  'tech.zapier': '應用程式連接',
  'tech.python': '數據處理',
  'tech.javascript': '網頁開發',
  'tech.openai': 'AI 整合',
  
  // Testimonials
  'testimonials.title': '客戶怎麼說',
  'testimonials.subtitle': '來自使用我們AI自動化解決方案的企業真實反饋',
  'testimonials.testimonial1.quote': 'AI Formula 幫助我們建立了一個自定義 WhatsApp 自動化系統，可以24/7處理客戶查詢。再也不會錯過訊息，我們的回應時間顯著改善。',
  'testimonials.testimonial1.author': '黃家明',
  'testimonials.testimonial1.service': '自定義自動化解決方案',
  'testimonials.testimonial1.company': '本地貿易公司',
  'testimonials.testimonial2.quote': '他們的團隊為我們建立了一個自定義商業自動化系統，連接我們的庫存、訂單和會計。現在一切運行順暢。',
  'testimonials.testimonial2.author': '陳小鳳',
  'testimonials.testimonial2.service': '商業自動化',
  'testimonials.testimonial2.company': '小型製造企業',
  'testimonials.testimonial3.quote': '他們為我們餐廳創建的自定義AI聊天機器人完美處理預訂和訂單。它懂廣東話和英語！',
  'testimonials.testimonial3.author': '林美玲',
  'testimonials.testimonial3.service': '自定義AI聊天機器人',
  'testimonials.testimonial3.company': '家庭餐廳',
  
  // Automation Journey
  'journey.title': '您的自動化之旅',
  'journey.subtitle': '我們經過驗證的4步流程確保成功實施自動化',
  'journey.step1.title': '發現諮詢',
  'journey.step1.description': '了解您的需求並識別自動化機會',
  'journey.step2.title': '策略設計',
  'journey.step2.description': '創建針對您業務流程的詳細藍圖',
  'journey.step3.title': '建構整合',
  'journey.step3.description': '開發並無縫整合您的自定義自動化解決方案',
  'journey.step4.title': '上線支援',
  'journey.step4.description': '部署您的解決方案並提供持續支援和優化',
  
  // Instructors
  'instructors.title': '認識我們的',
  'instructors.titleHighlight': '專家講師',
  'instructors.subtitle': '向結合深厚技術專長與真實商業經驗的行業領導者學習AI和自動化。',
  'instructors.experience': '經驗',
  'instructors.professionalJourney': '專業經歷',
  'instructors.teachingPhilosophy': '教學理念',
  'instructors.keyQualifications': '主要資格',
  'instructors.viewProfile': '查看完整檔案',
  
  // Kenneth - 第一位講師
  'instructors.sarah.name': 'Kenneth',
  'instructors.sarah.title': 'AI 行銷開發者與自動化專家',
  'instructors.sarah.specialty': 'AI 工具與行銷自動化',
  'instructors.sarah.experience': '4+ 年',
  'instructors.sarah.biography': 'Kenneth 是一位先驅性的AI行銷開發者，專精於尖端AI工具、自動化系統和策略實施。經過4年深入的AI學習，他已經掌握了通過人工智能和自動化技術轉變傳統行銷方法的藝術。',
  'instructors.sarah.philosophy': 'AI正在根本性地改變我們的生活和工作方式。未來屬於今天就擁抱AI的人。我幫助個人和企業在大眾跟上之前，通過掌握AI工具和自動化來搶得先機。',
  'instructors.sarah.qual1': 'AI 行銷自動化專家',
  'instructors.sarah.qual2': '高級AI工具實施',
  'instructors.sarah.qual3': '策略性AI業務整合',
  'instructors.sarah.qual4': '面向未來的行銷系統',
  
  // David - 第二位講師
  'instructors.david.name': 'David',
  'instructors.david.title': '商業自動化與AI整合專家',
  'instructors.david.specialty': '自動化與AI解決方案',
  'instructors.david.experience': '7+ 年',
  'instructors.david.biography': 'David是一位商業自動化專家，花了7年以上時間幫助公司消除過度工作並簡化營運。他專精於使用Make.com、n8n和AI工具創建強大的自動化工作流程。',
  'instructors.david.philosophy': '自動化應該解決真正的商業問題並減少過度工作。我幫助企業實施一體化AI解決方案來轉變營運。',
  'instructors.david.qual1': 'Make.com 與 n8n 自動化專家',
  'instructors.david.qual2': '業務流程優化',
  'instructors.david.qual3': 'AI驅動的內容管理',
  'instructors.david.qual4': '一體化業務解決方案',
  
  // Ken - 第三位講師
  'instructors.emily.name': 'Ken',
  'instructors.emily.title': '自定義業務開發者與AI自動化專家',
  'instructors.emily.specialty': '自定義編程與AI自動化',
  'instructors.emily.experience': '5+ 年',
  'instructors.emily.biography': 'Ken是一位熟練的自定義業務開發者，擁有5年以上的編程經驗，專精於創建量身定制的業務解決方案和AI自動化系統，幫助企業更快工作、更高效運行。',
  'instructors.emily.philosophy': '程式碼應該讓工作更快，讓企業運行更順暢。我創建整合AI自動化的自定義解決方案，消除瓶頸並加速業務流程。',
  'instructors.emily.qual1': '自定義業務應用程式開發',
  'instructors.emily.qual2': 'AI自動化整合專家',
  'instructors.emily.qual3': '性能優化專家',
  'instructors.emily.qual4': '快速開發解決方案',
  
  // Jason - 第四位講師
  'instructors.michael.name': 'Jason',
  'instructors.michael.title': '專業開發者與自定義自動化專家',
  'instructors.michael.specialty': '編程與自定義自動化',
  'instructors.michael.experience': '8+ 年',
  'instructors.michael.biography': 'Jason是一位專業開發者，擁有8年以上的編程經驗，專精於LLM聊天機器人開發、MCP整合和網頁應用程式。他一直在深入學習AI來提升編程技能。',
  'instructors.michael.philosophy': '沒有AI，就沒有生活！AI能改變的比你想像的更多。每個開發者都需要擁抱AI來保持相關性並創建非凡的解決方案。',
  'instructors.michael.qual1': 'LLM 聊天機器人開發專家',
  'instructors.michael.qual2': 'MCP 整合專家',
  'instructors.michael.qual3': '全端網頁開發',
  'instructors.michael.qual4': 'AI增強編程解決方案',
  
  // Contact
  'contact.title': '聯絡我們',
  'contact.subtitle': '準備好用AI轉型您的業務嗎？',
  'contact.form.title': '發送訊息給我們',
  'contact.form.description': '填寫下面的表格，我們將在24小時內回覆您',
  'contact.form.name': '全名',
  'contact.form.email': '電子郵件地址',
  'contact.form.message': '我們如何幫助您？',
  'contact.form.send': '發送訊息',
  'contact.info.emailUs': '電郵我們',
  'contact.info.emailDescription': '快速獲得問題回覆',
  'contact.info.callUs': '致電我們',
  'contact.info.phoneDescription': '星期一至五 上午9時至下午6時 香港時間',
  'contact.info.visitUs': '造訪我們',
  'contact.info.visitDescription': '預約會面',
  
  // Toast Messages
  'toast.messageSent': '訊息已發送！',
  'toast.messageDescription': '感謝您的關注。我們將在24小時內回覆您。',
  
  // Features
  'features.title': '為什麼選擇AI Formula？',
  'features.subtitle': '專為香港市場設計的專業AI培訓',
  'features.practical.title': '實用應用',
  'features.practical.desc': '真實商業場景和實踐項目',
  'features.expert.title': '專業講師',
  'features.expert.desc': '具有豐富經驗的行業專業人士',
  'features.support.title': '持續支持',
  'features.support.desc': '持續學習支持和社群',
  'features.local.title': '本地專注',
  'features.local.desc': '專為香港商業環境設計',
  
  // Courses
  'courses.title': '精選課程',
  'courses.subtitle': '全面的AI培訓課程',
  'courses.beginner': '初級',
  'courses.intermediate': '中級',
  'courses.advanced': '進階',
  'courses.hours': '小時',
  'courses.students': '學生',
  'courses.rating': '評分',
  'courses.enroll': '立即註冊',
  'courses.learnMore': '了解更多',
  
  // Footer
  'footer.company': 'AI Formula',
  'footer.description': '香港企業的專業AI培訓',
  'footer.links': '快速連結',
  'footer.courses': '課程',
  'footer.about': '關於',
  'footer.contact': '聯絡',
  'footer.support': '支援',
  'footer.legal': '法律',
  'footer.privacy': '隱私政策',
  'footer.terms': '服務條款',
  'footer.newsletter': '電子報',
  'footer.newsletter.desc': '獲取最新的AI更新和課程公告',
  'footer.newsletter.placeholder': '輸入您的電子郵件',
  'footer.newsletter.button': '訂閱',
  'footer.social': '關注我們',
  'footer.rights': '版權所有',
  
  // Course Details
  'course.duration': '課程時長',
  'course.level': '難度等級',
  'course.language': '語言',
  'course.certificate': '證書',
  'course.overview': '課程概述',
  'course.curriculum': '課程大綱',
  'course.instructor': '講師',
  'course.reviews': '評價',
  'course.whatYouLearn': '你將學到',
  'course.requirements': '要求',
  'course.includes': '本課程包含',
  'course.enroll': '註冊課程',
  'course.preview': '預覽課程',
  
  // Learning
  'learning.progress': '進度',
  'learning.completed': '已完成',
  'learning.continue': '繼續學習',
  'learning.start': '開始學習',
  'learning.next': '下一課',
  'learning.previous': '上一課',
  'learning.notes': '筆記',
  'learning.resources': '資源',
  'learning.quiz': '測驗',
  'learning.exercise': '練習',
  'learning.download': '下載',
  
  // Blog
  'blog.title': '最新見解',
  'blog.subtitle': 'AI Formula 專家見解',
  'blog.readMore': '閱讀更多',
  'blog.category': '類別',
  'blog.tags': '標籤',
  'blog.author': '作者',
  'blog.date': '日期',
  'blog.readTime': '閱讀時間',
  'blog.share': '分享',
  'blog.like': '喜歡',
  'blog.comment': '評論',
  
  // Auth
  'auth.login': '登入',
  'auth.signup': '註冊',
  'auth.email': '電子郵件',
  'auth.password': '密碼',
  'auth.confirmPassword': '確認密碼',
  'auth.forgotPassword': '忘記密碼？',
  'auth.rememberMe': '記住我',
  'auth.loginButton': '登入',
  'auth.signupButton': '註冊',
  'auth.or': '或',
  'auth.googleLogin': '使用Google繼續',
  'auth.facebookLogin': '使用Facebook繼續',
  'auth.hasAccount': '已有帳戶？',
  'auth.noAccount': '沒有帳戶？',
  'auth.loginDescription': '輸入您的電子郵件和密碼登入您的帳戶',
  'auth.signupDescription': '創建您的帳戶，開始與AI Formula一起學習',
  'auth.emailPlaceholder': '請輸入您的電子郵件地址',
  'auth.passwordPlaceholder': '請輸入您的密碼',
  'auth.confirmPasswordPlaceholder': '請再次輸入密碼',
  
  // Dashboard
  'dashboard.welcome': '歡迎回來',
  'dashboard.overview': '概述',
  'dashboard.myCourses': '我的課程',
  'dashboard.progress': '進度',
  'dashboard.achievements': '成就',
  'dashboard.settings': '設定',
  'dashboard.profile': '個人資料',
  'dashboard.notifications': '通知',
  'dashboard.billing': '帳單',
  'dashboard.support': '支援',
  
  // User Avatar Dropdown
  'userMenu.dashboard': '儀表板',
  'userMenu.settings': '設定',
  'userMenu.profile': '個人資料',
  'userMenu.signOut': '登出',
  'userMenu.greeting': '你好',
  
  // Common
  'common.loading': '載入中...',
  'common.error': '錯誤',
  'common.success': '成功',
  'common.warning': '警告',
  'common.info': '資訊',
  'common.save': '儲存',
  'common.cancel': '取消',
  'common.delete': '刪除',
  'common.edit': '編輯',
  'common.view': '查看',
  'common.download': '下載',
  'common.upload': '上傳',
  'common.search': '搜尋',
  'common.filter': '篩選',
  'common.sort': '排序',
  'common.reset': '重置',
  'common.apply': '套用',
  'common.close': '關閉',
  'common.open': '開啟',
  'common.yes': '是',
  'common.no': '否',
  'common.ok': '確定',
  'common.back': '返回',
  'common.next': '下一步',
  'common.previous': '上一步',
  'common.submit': '提交',
  'common.confirm': '確認',
  'common.more': '更多',
  'common.less': '更少',
  'common.show': '顯示',
  'common.hide': '隱藏',
  'common.expand': '展開',
  'common.collapse': '收合',
  
  // 工具頁面
  'tools.title': '推薦AI 工具',
  'tools.subtitle': '發現強大工具，提升您的生產力和創造力',
  'tools.categories.aiVideo': 'AI 影片工具',
  'tools.categories.dataTools': '數據工具', 
  'tools.categories.designTools': '設計工具',
  'tools.categories.marketingTools': 'AI 行銷工具',
  
  // Design Tools
  'tools.freepik.title': 'Freepik - 免費設計資源',
  'tools.freepik.description': '獲取數百萬免費向量圖、照片和圖形素材。不花大錢也能創造驚人視覺效果。',
  'tools.freepik.tag': '免費設計',
  'tools.freepik.visitSite': '訪問 Freepik',
  
  // Data Tools
  'tools.mem0.title': 'Mem0 - OpenMemory MCP',
  'tools.mem0.description': 'AI應用的高級記憶管理和對話持久化。構建具有上下文記憶的智能AI系統。',
  'tools.mem0.tag': 'AI記憶',
  'tools.mem0.visitSite': '訪問 Mem0',
  
  'tools.chat4data.title': 'Chat4Data - AI 網頁數據提取',
  'tools.chat4data.description': '通過聊天方式從任何網站提取結構化數據。無需編程，AI自動檢測並提取最有價值的數據。',
  'tools.chat4data.tag': '數據提取',
  'tools.chat4data.visitSite': '訪問 Chat4Data',
  
  // AI Video Tools
  'tools.hailuo.title': 'Hailuo AI - 頂級AI影片生成',
  'tools.hailuo.description': '免費使用Minimax的Hailuo 02，頂級AI影片工具，幾分鐘內將圖片轉換為驚艷HD影片。',
  'tools.hailuo.tag': 'AI影片',
  'tools.hailuo.visitSite': '訪問 Hailuo AI',
  
  'tools.higgsfield.title': 'Higgsfield AI - 視覺特效',
  'tools.higgsfield.description': 'AI驅動的攝影機控制和視覺特效工具。從爆炸到超現實轉換，創造電影級視覺效果。',
  'tools.higgsfield.tag': '視覺特效',
  'tools.higgsfield.visitSite': '訪問 Higgsfield',
  
  'tools.unstableml.title': 'UnstableML - AI 虛擬人',
  'tools.unstableml.description': '個性化AI虛擬人，用於產品展示、教程和UGC內容創作。克隆您的臉部和聲音。',
  'tools.unstableml.tag': 'AI虛擬人',
  'tools.unstableml.visitSite': '訪問 UnstableML',
  
  'tools.4dv.title': '4DV.AI - AI 影片平台',
  'tools.4dv.description': '先進的AI影片生成和編輯平台，提供專業級影片創作工具和效果。',
  'tools.4dv.tag': 'AI影片',
  'tools.4dv.visitSite': '訪問 4DV.AI',
  
  'tools.seaweedapt.title': 'Seaweed APT2 - 實時影片生成',
  'tools.seaweedapt.description': '自回歸對抗性後訓練，用於實時互動影片生成。以最小延遲串流高質量24fps影片。',
  'tools.seaweedapt.tag': '實時影片',
  'tools.seaweedapt.visitSite': '訪問 Seaweed APT',
  
  // 行銷工具
  'tools.headai.title': 'Head AI - 全球首個AI行銷專家',
  'tools.headai.description': '專業AI全面接管您的網紅和聯盟行銷。不只是工具，而是完整的AI行銷團隊，端到端處理營銷活動。',
  'tools.headai.tag': 'AI行銷',
  'tools.headai.visitSite': '訪問 Head AI',
  
  // 404 Page
  'notFound.title': '糟糕！找不到頁面',
  'notFound.subtitle': '您所尋找的頁面不存在',
  'notFound.description': '很抱歉，這種情況可能發生。頁面可能已移動或刪除，或您可能輸入了錯誤的網址。',
  'notFound.error404': '404',
  'notFound.pageNotFound': '頁面未找到',
  'notFound.quickLinks': '快速連結',
  'notFound.backToHome': '返回首頁',
  'notFound.contactSupport': '聯繫支援',
  'notFound.reportProblem': '報告問題',
  'notFound.currentPath': '尋找路於',
  'notFound.timestamp': '時間',
  'notFound.needHelp': '需要幫助？',
}

// 創建語言上下文
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 語言提供者組件
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh-HK');

  const getTranslations = (lang: Language): Translations => {
    return lang === 'zh-HK' ? zhTranslations : enTranslations;
  };

  const t = (key: string): string => {
    const translations = getTranslations(language);
    
    // First check if the full key exists as a flat key (for backwards compatibility)
    if (translations[key] && typeof translations[key] === 'string') {
      return translations[key] as string;
    }
    
    // Handle nested keys with dot notation
    if (key.includes('.')) {
      const keys = key.split('.');
      let value: any = translations;
      
      for (const nestedKey of keys) {
        if (value && typeof value === 'object' && nestedKey in value) {
          value = value[nestedKey];
        } else {
          return key; // Return the key if path doesn't exist
        }
      }
      
      return typeof value === 'string' ? value : key;
    }
    
    // Handle flat keys (backwards compatibility)
    const value = translations[key];
    return typeof value === 'string' ? value : key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    translations: getTranslations(language),
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// 自訂鉤子
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
